# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-12 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='sex',
            field=models.IntegerField(choices=[(0, 'Asian (Bangladesh)'), (1, 'Asian (Chinese)'), (2, 'Asian (Indian)'), (3, 'Asian (Other)'), (4, 'Asian (Pakistan)'), (5, 'Black (African)'), (6, 'Black (Caribbean)'), (7, 'Black (Other)'), (8, 'Mixed Background'), (9, 'Other Ethinicity'), (10, 'TBC'), (11, 'Traveller/Gypsy'), (12, 'White (English)'), (13, 'White (Irish)'), (14, 'White (Other)'), (13, 'White (Scottish)'), (14, 'White (Welsh)')], default=0),
        ),
    ]
