# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-12 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20170512_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
