# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-12 07:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_auto_20170512_0727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='notes',
        ),
        migrations.AddField(
            model_name='note',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.Person'),
        ),
    ]
