# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-12 08:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_auto_20170512_0808'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_1', models.CharField(max_length=100)),
                ('line_2', models.CharField(max_length=100)),
                ('line_3', models.CharField(max_length=100)),
                ('post_code', models.CharField(max_length=100)),
                ('area', models.IntegerField(choices=[(0, 'Badenoch and Strathspey'), (1, 'Caithness'), (2, 'Inverness and Nairn'), (3, 'Lochaber'), (4, 'Ross-shire'), (5, 'Skye'), (6, 'Sutherland')], default=0)),
                ('evidence', models.FileField(upload_to='client/address_evidence/')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Telephone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Home'), (1, 'Work'), (2, 'Mobile')], default=2)),
                ('number', models.CharField(max_length=100)),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.Person')),
            ],
        ),
    ]
