# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-12 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_address_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='type',
            field=models.IntegerField(choices=[(0, 'Client'), (1, 'Job Coach'), (2, 'Manager'), (3, 'Partner')], default=0),
        ),
    ]
