# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-12 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_person_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='client.Person')),
                ('birth_certificate', models.FileField(upload_to='client/birth_certs/')),
                ('social_work_involved', models.BooleanField()),
            ],
            bases=('client.person',),
        ),
    ]
