# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-12 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0013_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='known_as',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
