# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-12 10:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0016_auto_20170512_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='person',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
