# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-12 10:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0017_auto_20170512_1018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='created_by',
            new_name='modified_by',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='created_date',
            new_name='modified_date',
        ),
    ]
