# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-12 11:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0018_auto_20170512_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Address', to='client.Person'),
        ),
        migrations.AlterField(
            model_name='note',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Note', to='client.Person'),
        ),
        migrations.AlterField(
            model_name='telephone',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Telephone', to='client.Person'),
        ),
    ]
