# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-12 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0019_auto_20170512_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='social_work_involved',
            field=models.BooleanField(default=False),
        ),
    ]
