# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-12 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0023_auto_20170512_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note', to='client.Person'),
        ),
    ]
